---
- hosts: localhost
  vars_files:
    - ../../group_vars/all
  tasks:
    - name: get disks
      virtualDisk:
       login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
       get:
         fields: id
      register: get_disks_results
    - debug: var=get_disks_results['output']['get']

    - name: Create pool
      pool:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        createVSA:
          name: test_pool
          addPoolUnitParameters: ["poolUnit": "{{ get_disks_results['output']['get'][0] }}", "poolUnit": "{{ get_disks_results['output']['get'][1] }}"]
          #[{"poolUnit" : {"id" : "vdisk_1"}}, {"poolUnit" : {"id" : "vdisk_2"}}] 
          #["poolUnit": "{{ get_disks_results['output']['get'][0] }}", "poolUnit": "{{ get_disks_results['output']['get'][1] }}"]
      register: create_pool_results
    - debug: var=create_pool_results['output']

    - name: create Nas Server
      nasServer:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        create:
          name: nasServerFromPlaybook
          homeSP: {id: 'spa'}
          pool:  {id: "{{ create_pool_results['output']['createVSA']['id'] }}"}
          isMultiProtocolEnabled: false
      register: create_nas_server_results
    - debug: var=create_nas_server_results['output']

    - name: nfsServer creation
      nfsServer:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        create:
          nasServer: {id: "{{ create_nas_server_results['output']['create']['id'] }}"}
      register: create_nfs_server_results
    - debug: var=create_nfs_server_results['output']

    - name: create fileInterface
      fileInterface:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        create:
          nasServer: {id: "{{ create_nas_server_results['output']['create']['id'] }}"}
          ipPort: {id: "spa_eth0"}
          ipAddress: "{{ fileInterface_ip }}"
      register: file_interface_create_results
    - debug: var=file_interface_create_results['output']

    - name: create filesystem
      filesystem:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        create:
          name: file_system_created_by_playbook
          fsParameters:
            pool:  {id: "{{ create_pool_results['output']['createVSA']['id'] }}"}
            nasServer: {id: "{{ create_nas_server_results['output']['create']['id'] }}"}
            size: 5368709120 # size 5 GB
            supportedProtocols: 0
      register: file_system_create_results
    - debug: var=file_system_create_results['output']

    - name: create nfsShare
      nfsShare:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        create:
          storageResource: {'id': "{{ file_system_create_results['output']['create']['storageResource']['id'] }}"}
          name: nfsShareTestPlaybook
          path: '/'
      register: create_nfs_share_results
    - debug: var=create_nfs_share_results['output']
