---
- hosts: localhost
  vars_files:
    - ../../../group_vars/all
  tasks:
    - name: Create nasServer
      nasServer:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        create:
          name: "{{ nasServer_name }}"
          homeSP: {id: "{{ homeSP_id }}"}
          pool: {id: "{{ pool_id }}"}
      register: result1
    - debug: var=result1['output']

