---
- hosts: localhost
  vars_files:
    - ../../../group_vars/all
  tasks:
    - name: Create host
      host:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        create:
          type: "{{ host_type }}"
          name: "{{ host_name }}"
      register: result1
    - debug: var=result1['output']

    - name: Modify host
      host:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        modify:
          id: "{{ result1['output']['create']['id'] }}"
          name: "host_with_modified_name"
      register: result2
    - debug: var=result2['output']

    - name: Delete host
      host:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        delete:
          id: "{{ result1['output']['create']['id'] }}"
      register: result3
    - debug: var=result3['output']
