---
- hosts: localhost
  vars_files:
    - ../../../group_vars/all
  tasks:
    - name: Create iscsiPortal
      iscsiPortal:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        create:
          ethernetPort: {"id": "{{ ethernet_port_id }}"}
          ipAddress: "{{ iscsiPortal_ipAddress }}"
          netmask: "{{ iscsiPortal_netmask }}"
      register: result1
    - debug: var=result1

    - name: Modify iscsiPortal
      iscsiPortal:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        modify:
          id: "{{ result1['output']['create']['id'] }}"
          ipAddress: "{{ iscsiPortal_ipAddress }}"
      register: result2
    - debug: var=result2

    - name: Delete iscsiPortal
      iscsiPortal:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        delete:
          id: "{{ result1['output']['create']['id'] }}"
      register: result3
    - debug: var=result3
