---
- name: Run Windows Updates
  hosts: win
  tasks:
    - name: Running Windows update
      win_updates:
        category_names:
        - Application
        - Connectors
        - CriticalUpdates
        - DefinitionUpdates
        - DeveloperKits
        - FeaturePacks
        - Guidance
        - SecurityUpdates
        - ServicePacks
        - Tools
        - UpdateRollups
        - Updates
        reboot: yes
        #reboot_timeout: 420
