---
- hosts: localhost
  vars_files:
    - ../../../group_vars/all
  tasks:
    - name: Get fileInterfaces id
      commonGetPost:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        get:
          resource_type: fileInterface
          fields: id
      register: get_fileInterfaces_results
    - debug: var=get_fileInterfaces_results['output']['get']

    - name: Delete fileInterfaces
      fileInterface:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        delete:
          id: "{{ item['id'] }}"

      loop: "{{ get_fileInterfaces_results['output']['get'] }}"

      register: delete_fileInterfaces_results
    - debug: var=delete_fileInterfaces_results['output']
