---
- hosts: localhost
  vars_files:
    - ../../../group_vars/all
  tasks:
    
    - name: Modify lun
      lun:
        login:
          unityIP: "{{ unity_host }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        modifyLun:
          id: "{{ result1['output']['createLun']['storageResource']['id'] }}"
          name: "modified_name_by_playbook"
      register: result2
    - debug: var=result2