---
- hosts: localhost
  vars_files:
    - ../../../group_vars/all
  tasks:
    - name: Create nfsServer
      nfsServer:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        create:
          nasServer: {'id': "{{ nasServer_id }}"}
      register: result1
    - debug: var=result1['output']

    - name: Modify nfsServer
      nfsServer:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        modify:
          id: "{{ result1['output']['create']['id'] }}"
#          name: "modifyNameByPlaybook"
      register: result2
    - debug: var=result2['output']

    - name: Delete nfsServer
      nfsServer:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        delete:
          id: "{{ result1['output']['create']['id'] }}"
      register: result3
    - debug: var=result3['output']