---
- hosts: localhost
  vars_files:
    - ../../../group_vars/all
  tasks:
    - name: Create pool
      pool:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        createVSA:
          name: "{{ pool_name }}"
          addPoolUnitParameters: [{"poolUnit" : {"id" : "vdisk_1"}}, {"poolUnit" : {"id" : "vdisk_2"}}]
      register: result1
    - debug: var=result1['output']

    - name: Modify pool
      pool:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        modifyVSA:
          id: "{{ result1['output']['create']['id'] }}"
          name: "modifyNameByPlaybook"
      register: result2
    - debug: var=result2['output']

    - name: Delete pool
      pool:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        delete:
          id: "{{ result1['output']['create']['id'] }}"
      register: result3
    - debug: var=result3['output']
