---
- hosts: localhost
  vars_files:
    - ../../../group_vars/all
  tasks:
    - name: Modify pool
      pool:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        modifyVSA:
          id: "{{ pool_id }}"
          name: "modifyNameByPlaybook"

      register: result1
    - debug: var=result1['output']
